name: Java project with Maven
on:
  push:
    branches: ["main", "staging", "testbranch"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java Runtime
      uses: actions/setup-java
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: build with Maven
      run: mvn -B compile --file pom.xml